version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

workflows:
  version: 2
  all-tests:
    jobs:
      - php/phpunit-tests:
          e:
            name: php/php
            php-version: <<matrix.php-version>>
          matrix:
            parameters:
              php-version: [ "8.2", "8.3", "8.4" ]
      - php/composer-github:
          filters:
            tags:
              only:
                - /.*/
