version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

workflows:
  version: 2
  all-tests:
    jobs:
      - php/phpunit-tests:
          matrix:
            parameters:
              php-version: [ "8.0", "8.1", "8.2", "8.3" ]
      - php/composer-github:
          filters:
            tags:
              only:
                - /.*/
